# Generated by Django 5.2.1 on 2025-05-19 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_in_company', models.CharField(blank=True, help_text="Employer's role or position within the company (e.g., HR Manager, Recruiter).", max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number for the employer (optional).', max_length=25, null=True)),
                ('company', models.ForeignKey(help_text='The company this employer represents.', on_delete=django.db.models.deletion.CASCADE, related_name='employer_profiles', to='jobs.company')),
                ('user', models.OneToOneField(help_text='The user account associated with this employer profile.', on_delete=django.db.models.deletion.CASCADE, related_name='employer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employer Profile',
                'verbose_name_plural': 'Employer Profiles',
                'ordering': ['company', 'user__username'],
            },
        ),
    ]
