# Generated by Django 5.2.1 on 2025-05-20 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_jobposting_skills_required'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(auto_now_add=True, help_text='The date and time the application was submitted.')),
                ('job_posting', models.ForeignKey(help_text='The job posting for which the user applied.', on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='jobs.jobposting')),
                ('user_profile', models.ForeignKey(help_text='The profile of the user who applied.', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='profiles.userprofile')),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'ordering': ['-application_date'],
                'unique_together': {('user_profile', 'job_posting')},
            },
        ),
    ]
