# Generated by Django 5.2.1 on 2025-07-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_jobapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('entry', 'Entry-Level'), ('mid', 'Mid-Level'), ('senior', 'Senior')], max_length=10, null=True),
        ),
    ]
