# Generated by Django 5.2.1 on 2025-05-20 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='skills_required',
            field=models.ManyToManyField(blank=True, related_name='job_postings_requiring_skill', to='profiles.skill'),
        ),
    ]
